@@include('../assets/components/load-more/index.min.js')
@@include('../assets/components/confirm/index.min.js')
@@include('../assets/components/icon/index.min.js')
@@include('../assets/components/swipeout/index.min.js')
@@include('../assets/components/swipeout-button/index.min.js')
@@include('../assets/components/swipeout-item/index.min.js')